image:
  - Visual Studio 2019
environment:
  matrix:
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python -u .\\setup.py unittests"

after_test:
  - "%PYTHON%\\python -u .\\setup.py bdist_wheel"

artifacts:
  - path: dist
    name: python3_module_template
