version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.1
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          - v2-dependencies-

      - run:
          name: Install pandoc
          command: |
                    sudo apt-get update 
                    wget https://github.com/jgm/pandoc/releases/download/2.11.3.2/pandoc-2.11.3.2-1-amd64.deb
                    sudo dpkg -i pandoc-2.11.3.2-1-amd64.deb
          
      - run:
          name: Install tex
          command: |
                    sudo apt-get install -y texlive
                    sudo apt-get install -y texlive-latex-extra
                    sudo apt-get install -y texlive-xetex
                    sudo apt-get install -y dvipng
          
      - run:
          name: Install 7z, unrar
          command: |
                    sudo apt-get install -y p7zip-full
          
      - run:
          name: Install InkScape
          command: |
                    sudo apt-get install -y inkscape
          
      - run:
          name: Install graphviz
          command: |
                    sudo apt-get install -y graphviz
          
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install scipy scikit-learn

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python ./setup.py unittests

      - run:
          name: wheel
          command: |
            . venv/bin/activate
            python ./setup.py bdist_wheel
            mkdir -p test-reports/dist
            cp dist/*.whl test-reports/dist

#       - run:
#           name: documentation
#           command: |
#             . venv/bin/activate
#             python ./setup.py build_sphinx
#             
#       - run:
#           name: copy documentation
#           command: |
#             mkdir -p test-reports/doc
#             mkdir -p test-reports/pdf
#             zip -r -9  test-reports/doc/documentation_html.zip _doc/sphinxdoc/build/html
#             cp _doc/sphinxdoc/build/elatex/*.pdf test-reports/pdf
#             cp _doc/sphinxdoc/build/elatex/python*.tex* test-reports/pdf
            
      - store_artifacts:
          path: test-reports
          destination: test-reports